-- Скрипт сгенерирован Devart dbForge Studio Beta for MySQL, Версия 6.1.98.0
-- Домашняя страница продукта: http://www.devart.com/ru/dbforge/mysql/studio
-- Дата скрипта: 31.01.2014 16:07:42
-- Версия сервера: 5.6.14
-- Версия клиента: 4.1

SET NAMES 'utf8';

CREATE TABLE razor.channel_partner (
  id int(11) NOT NULL AUTO_INCREMENT,
  channel_name varchar(255) DEFAULT NULL,
  logo_url varchar(255) DEFAULT NULL,
  channel_type tinyint(3) UNSIGNED DEFAULT NULL,
  coverage varchar(255) DEFAULT NULL,
  contact_type varchar(255) DEFAULT NULL,
  payment_process varchar(255) DEFAULT NULL,
  payouts text DEFAULT NULL,
  damage_coverage varchar(255) DEFAULT NULL,
  traffic varchar(255) NOT NULL DEFAULT '0',
  commission double DEFAULT 0,
  listing_fees text DEFAULT NULL,
  privacy_policy varchar(255) DEFAULT NULL,
  terms_conditions varchar(255) DEFAULT NULL,
  selected tinyint(4) DEFAULT NULL,
  phone varchar(255) DEFAULT NULL,
  email varchar(255) DEFAULT NULL,
  office_address text DEFAULT NULL,
  description text DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 918
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(918, 'ByOwner', 'http://www.byowner.com/images/logo.png', 4, 'Global', NULL, NULL, 'No Information', NULL, '0', 0, 'The majority of postings on ByOwner are free, if however you post within in an area or category in which we charge a fee, you will be notified in advance of posting your item and will have the option to proceed.', 'http://www.byowner.com/privacypolicy', 'http://www.byowner.com/termsofuse', NULL, NULL, NULL, NULL, NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(919, 'Flee Winter', 'http://www.fleewinter.co.uk/images/logo.jpg', 4, 'Global', NULL, NULL, '4 weeks before arrival the client', NULL, '0', 0, 'Free Listing+ commision(The size of the commission varies depending on a number of factors such as the pricing of the accommodation, the typical length of stay and whether you are exclusive to us).', 'http://www.fleewinter.co.uk/cape_town/terms.php', 'http://www.fleewinter.co.uk/cape_town/terms.php', NULL, '0207 112 0019 in the UK <br /> +44 207 112 0019 out side UK', NULL, 'Fleewinter Ltd, 49 Stilehall Gardens, London, W4 3BT, United Kingdom', NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(920, 'Holiday Rentals', 'http://www.holidayrentals.com/images/txt/logo.png', 2, 'Global', NULL, NULL, 'Renters would pay you directly. No commission to holidayrentals.com', NULL, '0', 0, 'Standard: $155\nPremier: $309\nPlatinum: $479', 'http://www.holidayrentals.com/privacy-policy.php', 'http://www.holidayrentals.com/disclaimer.php', NULL, '+1-908-470-104', NULL, '90 Washington Valley Road\nBedminster, NJ - 07921\nUSA', NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(921, 'Paradizo', 'http://static.paradizo.com/assets/logo_paradizo.png', 4, 'Global', NULL, NULL, 'Must contact site', NULL, '0', 0, 'Must contact site', 'http://paradizo.com/terms.html#Privacy', 'http://paradizo.com/terms.html#Terms', NULL, '+34-935 045 631', NULL, 'Av. Alcalde Barnils, 64-68 4ºD\n08174 Sant Cugat del Vallès (Barcelona)\nSpain', NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(922, 'Travel Direct', 'http://www.traveldirect.nl/images/img_title.gif', 3, 'Global', NULL, NULL, 'Must contact the web site', NULL, '0', 0, 'Must contact the web site', 'No Information', 'No Information', NULL, NULL, NULL, 'Keizersgracht 237, \nAmsterdam 1016EA', NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(923, 'Wantizen', 'http://www.wantizen.com/img/logo.png', 2, 'Global', NULL, NULL, 'lease contact our representative at support@wantizen.com', NULL, '0', 0, 'Must contact the web site, but it is free to sign up', 'No Information', 'http://www.wantizen.com/site/termsAndConditions', NULL, ' 206-497-9216', NULL, 'Vancouver, British Columbia, Canada.', NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(924, 'Wimdu', 'No Information', 2, 'Global', NULL, NULL, '24 hours after the start of his stay in the rented accommodation.', NULL, '0', 0, 'Free to list', 'http://www.wimdu.com/aboutus#about-us-terms-and-privacy', 'http://www.wimdu.com/aboutus#about-us-terms-and-privacy', NULL, NULL, NULL, 'Ohlauer Str. 43 \n10999 Berlin, Germany', NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(925, 'Blue Sky Overseas sl', 'http://clickandrent.co.uk/en/images/headerCWW.jpg', 2, 'Global', NULL, NULL, 'Payments is between clients and travelers.', NULL, '0', 0, 'speak to staff about this, as it depends on how many properties, the location of the properties etc.', 'http://clickandrent.co.uk/en/privacy_policy.php', 'http://clickandrent.co.uk/en/terms.php', NULL, NULL, NULL, NULL, NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(926, 'Marketquest Ltd', 'No Information', 4, 'Global', NULL, NULL, 'No Information', NULL, '0', 0, 'Standard Listing for 1st Year FREE \nFeatured Listings: 6 Months: £32 \nFeatured Listings: 1 Year: £49 \nFeatured Listings for 2 Years : £75', 'http://www.primeholidayresorts.com/disclaimer.aspx', 'http://www.primeholidayresorts.com/disclaimer.aspx', NULL, '+44 (0)20 8133 2928', NULL, '5 Hines Lane\nComberton\nCambridge, CB23 7BZ\nUnited Kingdom', NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(927, 'Marketquest Ltd', 'No Information', 2, 'Global', NULL, NULL, 'No Information', NULL, '0', 0, 'Standard Listing: 1st Year FREE + 1 Year: £29\nFeatured Listings: 6 Months: £32 \nFeatured Listings: 1 Year: £49 \nFeatured Listings: 2 Years: £75\nFeatured Listings: 3 Years: £99\nMultiple Listings: must contact', 'http://www.primeholidayrentals.com/disclaimer.aspx', 'http://www.primeholidayrentals.com/disclaimer.aspx', NULL, '+44 (0)20 8133 2928', NULL, '5 Hines Lane\nComberton\nCambridge, CB23 7BZ\nUnited Kingdom', NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(928, 'Marketquest Ltd', 'No Information', 4, 'Global', NULL, NULL, 'No Information', NULL, '0', 0, 'Standard Listing: 1st Year FREE + 1 Year: £29 \nFeatured Listings: 6 Months: £32 \nFeatured Listings: 1 Year: £49 \nFeatured Listings: 2 Years: £75', 'http://www.primeholidayresorts.com/disclaimer.aspx', 'http://www.primeholidayresorts.com/disclaimer.aspx', NULL, '+44 (0)20 8133 2928', NULL, '5 Hines Lane\nComberton\nCambridge, CB23 7BZ\nUnited Kingdom', NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(929, 'Marketquest Ltd', 'No Information', 4, 'Global', NULL, NULL, 'No Information', NULL, '0', 0, 'Standard Listing: 1st Year FREE + 1 Year: £29 \nFeatured Listings: 6 Months: £32 \nFeatured Listings: 1 Year: £49 \nFeatured Listings: 2 Years:£75', 'http://www.primeholidayresorts.com/disclaimer.aspx', 'http://www.primeholidayresorts.com/disclaimer.aspx', NULL, '+44 (0)20 8133 2928', NULL, '5 Hines Lane\nComberton\nCambridge, CB23 7BZ\nUnited Kingdom', NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(930, 'Marketquest Ltd', 'No Information', 1, 'Global', NULL, NULL, 'No Information', NULL, '0', 0, 'Standard Listing: 6 Months Free + 6 Months: 19 GBP \nFeatured Listings: 6 Months: 32 GBP \nFeatured Listings: 1 Year: 49 GBP \nFeatured Listings: 2 Years: 75 GBP', 'http://www.primepropertyforsale.com/disclaimer.aspx', 'http://www.primepropertyforsale.com/disclaimer.aspx', NULL, '+44 (0)20 8133 2928', NULL, '5Hines Lane\nComberton\nCambridge, CB23 7BZ\nUnited Kingdom', NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(931, 'Marketquest Ltd', 'No Information', 4, 'Global', NULL, NULL, 'No Information', NULL, '0', 0, 'Standard Listing/1 Year: £15(1st Year FREE) \nFeatured Listings/6 Months: £32 \nFeatured Listings/1 Year: £49 \nFeatured Listings/ 2 Years:£75', 'http://www.housesittersdirect.com/disclaimer.aspx', 'http://www.housesittersdirect.com/disclaimer.aspx', NULL, '+44 (0)20 8133 2928', NULL, '5 Hines Lane\nComberton\nCambridge, CB23 7BZ\nUnited Kingdom', NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(932, 'Black tomato', NULL, 4, 'Global', NULL, NULL, 'N/A', NULL, '0', 0, 'N/A', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(933, 'Black tomato', NULL, 2, 'Global', NULL, NULL, 'Must contact them', NULL, '0', 0, 'Must contact them', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(934, 'Apartments Apart', NULL, 2, 'Global', NULL, NULL, 'Must contact them', NULL, '0', 0, 'Must contact them', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(935, 'Booking.com', NULL, 4, 'Global', NULL, NULL, 'N/A', NULL, '0', 0, 'N/A', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(936, 'Vakast', NULL, 4, 'Global', NULL, NULL, 'Must contact site', NULL, '0', 0, 'Must contact site', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(937, 'VIP Holidays', NULL, 4, 'Global', NULL, NULL, 'N/A', NULL, '0', 0, 'N/A', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(938, '2 Travel', NULL, 4, 'Global', NULL, NULL, 'N/A', NULL, '0', 0, 'N/A', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(939, 'A Vakanties', NULL, 2, 'Global', NULL, NULL, 'N/A', NULL, '0', 0, 'N/A', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(940, 'A Vakanties', NULL, 2, 'Global', NULL, NULL, 'N/A', NULL, '0', 0, 'N/A', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(941, 'A Vakanties', NULL, 2, 'Global', NULL, NULL, 'N/A', NULL, '0', 0, 'N/A', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(942, 'A Vakanties', NULL, 2, 'Global', NULL, NULL, 'N/A', NULL, '0', 0, 'N/A', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(943, 'A Vakanties', NULL, 2, 'Global', NULL, NULL, 'N/A', NULL, '0', 0, 'N/A', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(944, 'A Vakanties', NULL, 2, 'Global', NULL, NULL, 'N/A', NULL, '0', 0, 'N/A', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(945, 'A Vakanties', NULL, 2, 'Global', NULL, NULL, 'N/A', NULL, '0', 0, 'N/A', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(946, 'A Vakanties', NULL, 2, 'Global', NULL, NULL, 'N/A', NULL, '0', 0, 'N/A', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(947, 'A Vakanties', NULL, 2, 'Global', NULL, NULL, 'N/A', NULL, '0', 0, 'N/A', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(948, 'Book2travel B.V', NULL, 4, 'Global', NULL, NULL, 'N/A', NULL, '0', 0, 'N/A', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(949, 'Book2travel B.V', NULL, 2, 'Global', NULL, NULL, 'N/A', NULL, '0', 0, 'N/A', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(950, 'Budgetair', NULL, 4, 'Global', NULL, NULL, 'N/A', NULL, '0', 0, 'N/A', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(951, 'Dagjeweg BV', NULL, 2, 'Global', NULL, NULL, 'N/A', NULL, '0', 0, 'N/A', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(952, 'Digera', NULL, 2, 'Global', NULL, NULL, 'N/A', NULL, '0', 0, 'N/A', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(953, 'O&S Vakanties', NULL, 2, 'Global', NULL, NULL, 'N/A', NULL, '0', 0, 'N/A', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(954, 'Travelchoosers BV', NULL, 4, 'Global', NULL, NULL, 'N/A', NULL, '0', 0, 'N/A', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(955, 'Tribble', NULL, 4, 'Global', NULL, NULL, 'N/A', NULL, '0', 0, 'N/A', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(956, 'Vakantieparken.nl', NULL, 2, 'Global', NULL, NULL, 'N/A', NULL, '0', 0, 'N/A', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(957, 'Vliegwinkel', NULL, 4, 'Global', NULL, NULL, 'N/A', NULL, '0', 0, 'N/A', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(958, 'Aol Travel', NULL, 2, 'Global', NULL, NULL, 'N/A', NULL, '0', 0, 'N/A', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(959, 'Yahoo Travel', NULL, 2, 'Global', NULL, NULL, 'N/A', NULL, '0', 0, 'N/A', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(960, 'ROOMLR B.V.', NULL, 2, 'Global', NULL, NULL, 'N/A', NULL, '0', 0, 'N/A', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(961, 'Roomorama', NULL, 2, 'Global', NULL, NULL, 'After the booking has been processed, Hosts will receive a confirmation email with the contact details of his/her Guest. The Guest will also received a confirmation email with the 6-digit payment code. Roomorama will process the payment to the Host on the agreed check in date (after the Guest has successful checked in).', NULL, '0', 0, 'Free', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(962, 'Summo Retreats', NULL, 2, 'Global', NULL, NULL, 'must contact the website', NULL, '0', 0, 'Must contact the web site', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(963, 'Washington Time', NULL, 1, 'Global', NULL, NULL, 'Must contact the web site', NULL, '0', 0, 'Must contact the web site', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(964, 'Mombaerts', NULL, 2, 'Global', NULL, NULL, 'must contact them', NULL, '0', 0, 'must contact them', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(965, 'Holiday Velvet', NULL, 2, 'Global', NULL, NULL, 'Some owners ask for the full balance payment before arrival, sometimes as far as 60 days before arrival.', NULL, '0', 0, 'Free to list', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(966, 'Flipkey', NULL, 2, 'Global', NULL, NULL, 'Payment is held until at least 24 hours after guest check-in. After payment is released, it will be processed and deposited into your bank account within 3-5 business days.', NULL, '0', 0, 'It’s free to advertise on FlipKey and TripAdvisor. they charge a 3% commission fee on each booking.', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(967, 'Marketquest Ltd', NULL, 4, 'Global', NULL, NULL, 'No Information', NULL, '0', 0, 'Standard Listing: 1st Year FREE \nFeatured Listings: 6 Months £32 \nFeatured Listings: 1 Year: £49 \nFeatured Listings: 2 Years : £75', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(968, 'Marketquest Ltd', NULL, 4, 'Global', NULL, NULL, 'No Information', NULL, '0', 0, 'Standard Listing: 1st Year FREE + 1 Year:29 GBP \nFeatured Listings: 6 Months:32 GBP \nFeatured Listings: 1 Year:49 GBP \nFeatured Listings: 2 Years:75 GBP', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(969, 'Milq Media', NULL, 2, 'Global', NULL, NULL, 'must contact them', NULL, '0', 0, 'must contact them', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(970, 'Poppup BV.', NULL, 2, 'Global', NULL, NULL, 'pay directly to the partner, without the intervention of Boekeenvakantiehuisje.nl.', NULL, '0', 0, 'must contact them', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(971, 'ROAS', NULL, 2, 'Global', NULL, NULL, 'must contact them', NULL, '0', 0, 'must contact them', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(972, 'Tera BV', NULL, 2, 'Global', NULL, NULL, 'must contact them', NULL, '0', 0, 'must contact them', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(973, 'Friendly Rentals', NULL, 2, 'Global', NULL, NULL, 'No Information, must contact them', NULL, '0', 0, 'No Information Must contact them', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(974, 'Only Apartments', NULL, 2, 'Global', NULL, NULL, 'In the process of making a reservation, all you have to pay online is the booking fee. The rest (the rent fee) will be paid directly to the property owner', NULL, '0', 0, 'Free', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(975, '9flats', NULL, 2, 'Global', NULL, NULL, '24 hours after the guest has checked into the accommodation', NULL, '0', 0, 'Free to list+ normally 15% of the accommodation price; 9flats, however, reserves the right to change this commission at times in favor of the host as part of special promotions and discounts.', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(976, 'Interholidayhomes', NULL, 2, 'Global', NULL, NULL, 'No Information on the website', NULL, '0', 0, 'No Information on the website', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(977, 'Zoover', NULL, 4, 'Global', NULL, NULL, 'Must contact them', NULL, '0', 0, 'Must contact them', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(978, 'Holidayspot', NULL, 2, 'Europe/ Africa/ USA', NULL, NULL, 'N/A', NULL, '0', 0, 'N/A', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(979, 'Cities Reference', NULL, 2, 'Europe/ USA', NULL, NULL, 'Cash payment to you is made in full upon the traveler''s arrival at your apartment, after having verified the condition of the apartment and before receiving the keys to it.', NULL, '0', 0, 'Free to list', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(980, 'Marketquest Ltd', NULL, 4, 'Europe/ USA', NULL, NULL, 'No Information', NULL, '0', 0, 'Standard Listing/1st: Year FREE \nFeatured Listings/1 Year:49 GBP \nFeatured Listings/2 Years:75 GBP \nFeatured Listings/3 Years:99 GBP', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(981, 'Euroflats', NULL, 2, 'Europe/ UK', NULL, NULL, 'N/A', NULL, '0', 0, 'N/A', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(982, 'Shevana', NULL, 2, 'Europe/ UK', NULL, NULL, 'N/A', NULL, '0', 0, 'N/A', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(983, 'Villa Select', NULL, 2, 'Europe/ Caribbean Islands/ Thailand', NULL, NULL, 'contact becci@villaselect.com or call us on +44 (0)1789 764 909.', NULL, '0', 0, 'contact becci@villaselect.com or call us on +44 (0)1789 764 909.', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(984, 'Hockxs Marketing B.V', NULL, 2, 'Europe/ Netherlands', NULL, NULL, 'full payment will receive before the check in', NULL, '0', 0, 'Advertising costs € 9, - per month with a minimum of 5 months.', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(985, 'Hockxs Marketing B.V', NULL, 2, 'Europe/ Netherlands', NULL, NULL, 'full payment will receive before the check in', NULL, '0', 0, 'Advertising costs € 9, - per month with a minimum of 5 months.', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(986, 'Freelance holiday', NULL, 2, 'Mallorca/ Mediterranean Islands', NULL, NULL, 'N/A', NULL, '0', 0, 'N/A', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(987, 'Marketquest Ltd', NULL, 4, 'Europe', NULL, NULL, 'No Information', NULL, '0', 0, 'Free listing', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(988, 'Marketquest Ltd', NULL, 4, 'Europe', NULL, NULL, 'No Information', NULL, '0', 0, 'Standard Listing: 1st Year FREE + 1 Year : 29 GBP \nFeaFeatured Listings: 1 Year : 49 GBP \nFeaFeatured Listings: 2 Years;75 GBP \nFeatured Listings: 3 Years: 99 GBP', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(989, 'Quality Villas', NULL, 2, 'Europe', NULL, NULL, 'must contact the website', NULL, '0', 0, 'must contact the website', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(990, 'Bungalowpark Zoeken', NULL, 2, 'Europe', NULL, NULL, 'N/A', NULL, '0', 0, 'N/A', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(991, 'Immorent', NULL, 2, 'Europe', NULL, NULL, 'N/A', NULL, '0', 0, 'N/A', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(992, 'Online Bridge LLC', NULL, 2, 'Europe', NULL, NULL, 'N/A', NULL, '0', 0, 'N/A', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(993, 'Villa Vacant BV', NULL, 2, 'Europe', NULL, NULL, 'N/A', NULL, '0', 0, 'N/A', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(994, 'Marketquest Ltd', NULL, 2, 'Europe', NULL, NULL, 'No Information', NULL, '0', 0, 'Standard Listing per Month: £5 \nFeatured Listings/6 Months: £32 \nFeatured Listings/1 Year: £49 \nFeatured Listings/ 2 Years: £75', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(995, '3rd Millennium', NULL, 4, 'Europe', NULL, NULL, 'must contact the website', NULL, '0', 0, 'must contact the website', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(996, 'Bungalow.net', NULL, 2, 'Europe', NULL, NULL, 'must contact the website', NULL, '0', 0, 'Free listing', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(997, 'Loving Apartments', NULL, 2, 'Europe', NULL, NULL, 'After Reservation', NULL, '0', 0, 'Free', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(998, 'Holiday rental Hamburg GmbH', NULL, 2, 'Europe', NULL, NULL, 'After the guest has begun his/her stay in your property. This gives you and your guest the maximum security. When the guest pays a first installment payment of 25% (hence, he or she has booked more than 45 days ahead of the beginning of the stay) we will transfer the 25% minus our commission more quickly to your account.', NULL, '0', 0, 'no sign up fees only15% commission plus potentially necessary value added tax. If you are an agency and/or you have to offer more than a couple of houses, contact us straight away.', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(999, 'Marketquest Ltd', NULL, 4, 'Europe', NULL, NULL, 'No Information', NULL, '0', 0, '1st Year FREE + 1 Year 29 GBP \nFeatured Listings: 1 Year 49 GBP \nFeatured Listings: 2 Years 75 GBP \nFeatured Listings: 3 Years 99 GBP', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(1000, 'AlterKeys', NULL, 2, 'Europe', NULL, NULL, '24 hours after the check-in of the guest at the accommodation, on the condition that there has been no reason to terminate the contract.', NULL, '0', 0, 'Its free, but they deduct a commission from each payment, to cover the costs of managing the payments for each guest and maintaining the website.', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(1001, 'Bungalow.net', NULL, 4, 'Europe', NULL, NULL, 'Its in Dutch, Must contact the website', NULL, '0', 0, 'Its in dutch Must contact the web site', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(1002, 'Anyfreindofours', NULL, 2, 'Europe', NULL, NULL, 'The Company will transfer the monies less the Commission to the bank account of the Merchant two UK business days after the first day of the rental period.', NULL, '0', 0, 'It’s free to join and as a member you can rent out your property and rent other members'' properties across the network Pay as little as 7.5% commission by bringing 10 of your close friends and family into our community.', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(1003, 'Summer Support', NULL, 4, 'Balearic Islands', NULL, NULL, 'must contact them', NULL, '0', 0, 'must contact them', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(1004, 'Summer Support', NULL, 4, 'Croatian Riviera', NULL, NULL, 'must contact them', NULL, '0', 0, 'must contact them', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(1005, 'Vakantiehuis-Bretagne.com', NULL, 2, 'France', NULL, NULL, 'N/A', NULL, '0', 0, 'N/A', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(1006, 'Vakantiehuis-Provence.com', NULL, 2, 'France', NULL, NULL, 'N/A', NULL, '0', 0, 'N/A', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(1007, 'Vakantiehuizen B.V.', NULL, 2, 'France', NULL, NULL, 'N/A', NULL, '0', 0, 'N/A', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(1008, 'Rent Villas France', NULL, 2, 'France', NULL, NULL, 'complete the form,and one of their agents will contact shortly.', NULL, '0', 0, 'complete the form,and one of their agents will contact shortly.', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(1009, 'Vakantiehuis-Normandie.nl', NULL, 2, 'France/ Normandy', NULL, NULL, 'N/A', NULL, '0', 0, 'N/A', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(1010, 'Vakantiehuizen B.V.', NULL, 2, 'Italy', NULL, NULL, 'N/A', NULL, '0', 0, 'N/A', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(1011, 'Summer Support', NULL, 4, 'Italy', NULL, NULL, 'must contact them', NULL, '0', 0, 'must contact them', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(1012, 'Summer Support', NULL, 4, 'Italy', NULL, NULL, 'must contact them', NULL, '0', 0, 'must contact them', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(1013, 'Mallorca Farmhouse', NULL, 2, 'Mallorca', NULL, NULL, 'must contact the website', NULL, '0', 0, 'Must contact the website', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(1014, 'Camps Bay Online', NULL, 4, 'South Africa', NULL, NULL, 'Must contact site', NULL, '0', 0, 'Must contact site', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(1015, 'Capsol Rentals', NULL, 4, 'South Africa', NULL, NULL, 'Must contact site', NULL, '0', 0, 'Must contact site', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(1016, 'Classic Travel', NULL, 3, 'South Africa', NULL, NULL, 'Must contact site', NULL, '0', 0, 'Must contact site', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(1017, 'Come to Cape Town', NULL, 4, 'South Africa', NULL, NULL, 'Must contact site', NULL, '0', 0, 'commission basis\n&\nStandard Rates\n1 year @ R990\n2 years@ R1590\nBulk Discounts may apply for multiple properties!', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(1018, 'Escape 4 Africa', NULL, 3, 'South Africa', NULL, NULL, 'N/A', NULL, '0', 0, 'N/A', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(1019, 'Perfect Hideaways', NULL, 4, 'South Africa', NULL, NULL, 'N/A', NULL, '0', 0, 'N/A', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(1020, 'StayPlayEat', NULL, 3, 'South Africa', NULL, NULL, 'N/A', NULL, '0', 0, 'N/A', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(1021, 'Book Cape Town', NULL, 4, 'South Africa', NULL, NULL, 'Book Cape Town will take a 50% deposit of the total amount quoted by Book Cape Town to confirm all bookings, +Book Cape Town is entitled to retaining the agreed commission before paying the balance of the deposit into the supplier’s bank account', NULL, '0', 0, 'work on a commission basis (STO Rates), and therefore we do not charge a listing fee', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(1022, 'Cape luxury accommodation', NULL, 4, 'South Africa', NULL, NULL, 'Must contact site', NULL, '0', 0, 'Free listing + commision', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(1023, 'Cape Luxury Stay', NULL, 4, 'South Africa', NULL, NULL, 'No Information', NULL, '0', 0, 'Free:R0.00 (for 36months) .Feature:R1825 (for 12months)', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(1024, 'My Leisure Group', NULL, 2, 'South Africa', NULL, NULL, 'Must contact site', NULL, '0', 0, 'Must contact site', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(1025, 'Red Cherry', NULL, 4, 'South Africa', NULL, NULL, 'Must contact site', NULL, '0', 0, 'Must contact site', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(1026, 'SA-Villas.com', NULL, 2, 'South Africa', NULL, NULL, 'Must contact site to discuss each listing. They are quite selective.', NULL, '0', 0, 'Depend on the listing', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(1027, 'Sense Of The World', NULL, 2, 'South Africa', NULL, NULL, 'link is not working', NULL, '0', 0, 'Link is not working', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(1028, 'Villas in Cape Town', NULL, 2, 'South Africa', NULL, NULL, 'Must contact the web site', NULL, '0', 0, 'Must contact the web site', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(1029, 'Just Villas', NULL, 4, 'South Africa', NULL, NULL, 'Must contact site', NULL, '0', 0, 'Must contact site', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(1030, 'Kapstadt Travel', NULL, 4, 'South Africa', NULL, NULL, 'N/A', NULL, '0', 0, 'N/A', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(1031, 'Nox Rentals', NULL, 4, 'South Africa', NULL, NULL, 'N/A', NULL, '0', 0, 'N/A', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(1032, 'Sleeping-OUT', NULL, 4, 'South Africa', NULL, NULL, 'Only a 15% commission on confirmed bookings only. Payments normally made to you within 48 hours of confirmation.', NULL, '0', 0, 'No listing fee,Only a 15% commission on confirmed bookings.', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(1033, 'Summer Villa Escapes', NULL, 1, 'South Africa', NULL, NULL, 'No Information', NULL, '0', 0, '6 month listing - Posh Villas International\nR399.00, 1 year Listing- Posh Villas International R599.00, 1 Year Listing - Multiple site Listing -Special R599.00, 2 year Listing - Posh Villas International R899.00', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(1034, 'Gran Alacant', NULL, 2, 'Spain', NULL, NULL, 'N/A', NULL, '0', 0, 'N/A', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(1035, 'Vakantiehuizen B.V.', NULL, 2, 'Spain', NULL, NULL, 'N/A', NULL, '0', 0, 'N/A', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(1036, 'Edge Retreats', NULL, 4, 'UK', NULL, NULL, 'N/A', NULL, '0', 0, 'N/A', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(1037, 'Kodomo', NULL, 4, 'UK', NULL, NULL, 'N/A', NULL, '0', 0, 'N/A', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(1038, 'Eppraisal', NULL, 1, 'USA', NULL, NULL, 'Must contact site to discuss each listing', NULL, '0', 0, 'Must contact site to discuss each listing', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(1039, 'Condo.com', NULL, 4, 'USA', NULL, NULL, 'must contact the website', NULL, '0', 0, 'FREE/Month: \nUpgrades \nListing included on Houses.com and Property.com FREE\nFeatured in Search Results"Receive up to 5x the number of leads" : $49.95\nFREE/Year:\nUpgrades \nListing included on Houses.com and Property.com FREE\nFeatured in Search Results"Receive up to 5x the number of leads": $99.95', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(1040, 'Corporate Housing', NULL, 4, 'USA', NULL, NULL, 'Must contact site to discuss each listing', NULL, '0', 0, 'Must contact site to discuss each listing', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(1041, 'Homes.com', NULL, 4, 'USA', NULL, NULL, 'must contact the website', NULL, '0', 0, 'must contact the website', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(1042, 'Houses.com', NULL, 4, 'USA', NULL, NULL, 'allows free posting. No booking.', NULL, '0', 0, 'FREE/Month: \nUpgrades \nListing included on Houses.com and Property.com FREE\nFeatured in Search Results"Receive up to 5x the number of leads" : $49.95\nFREE/Year:\nUpgrades \nListing included on Houses.com and Property.com FREE\nFeatured in Search Results"Receive up to 5x the number of leads": $99.95', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(1043, 'Property.com', NULL, 4, 'USA', NULL, NULL, 'must contact the website', NULL, '0', 0, 'must contact the website', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(1044, 'RedAwning', NULL, 2, 'USA', NULL, NULL, 'They only provide reservations. No leads.', NULL, '0', 0, 'No advertising or setup costs.only pay a commission(15% of the Gross Rent)on reservations.', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(1045, 'SpliVR', NULL, 2, 'USA', NULL, NULL, 'upon confirmation of a Booking, the Renter will pay the Owner through a transaction facilitated by Company in accordance with the payment terms of the Booking.', NULL, '0', 0, 'listing link doesn''t work', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(1046, 'ForRent', NULL, 4, 'USA', NULL, NULL, 'Payment can be processed by the Supplier or by ForRent.com. If payment processed by ForRent. Payout will be 24 hours after guest check in.', NULL, '0', 0, 'INTERMEDIATE LISTING $100. DELUXE LISTING $150', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(1047, 'BookingsMade-Easy', NULL, 4, 'Website is not Working', NULL, NULL, 'websit is not working', NULL, '0', 0, 'websit is not working', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO channel_partner(id, channel_name, logo_url, channel_type, coverage, contact_type, payment_process, payouts, damage_coverage, traffic, commission, listing_fees, privacy_policy, terms_conditions, selected, phone, email, office_address, description) VALUES
(1048, 'Beach House Travel', NULL, 4, 'Website is under Construction', NULL, NULL, 'Websit is Under Construction', NULL, '0', 0, 'Websit is Under Construction', NULL, NULL, NULL, NULL, NULL, NULL, NULL);